CaseItauWeb/Controllers/FundoController.cs
using CaseItauWeb.DAL;
using CaseItauWeb.Models;
using CaseItauWeb.Utils;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CaseItauWeb.Controllers
{
    public class FundoController : Controller
    {
        private readonly FundoDAL _fundoDAL = new FundoDAL();
        public ActionResult Index()
        {
            try
            {
                var getFundos = _fundoDAL.GetAllFundos();
                return View(getFundos);
            }
            catch (ArgumentException ex)
            {
                ViewBag.Alert = ex.Message;
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.Alert = Constants.Error();
                return View();
            }
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(FundoModel fundo)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();
                _fundoDAL.RegisterFundo(fundo);
                return RedirectToAction("Index");
            }
            catch (ArgumentException ex)
            {
                ViewBag.Alert = ex.Message;
                return View("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Alert = Constants.Error();
                return View("Index");
            }
        }

        public ActionResult Edit(int id)
        {
            try
            {
                var result = _fundoDAL.GetFundo(id.ToString());
                return View(result);
            }
            catch (ArgumentException ex)
            {
                ViewBag.Alert = ex.Message;
                return View("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Alert = Constants.Error();
                return View("Index");
            }
        }

        [HttpPost]
        public ActionResult Edit(int id, FundoModel fundo)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();
                if (_fundoDAL.UpdateFundo(id.ToString(), fundo))
                    return RedirectToAction("Index");
                else
                    throw new ArgumentException(Constants.FundsNotUpdate());
            }
            catch (ArgumentException ex)
            {
                ViewBag.Alert = ex.Message;
                return View("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Alert = Constants.Error();
                return View("Index");
            }
        }

        public ActionResult EditPatrimony(int id)
        {
            var result = _fundoDAL.GetFundo(id.ToString());
            return View(result);
        }
        [HttpPost]
        public ActionResult EditPatrimony(int id, FundoModel value)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();
                if (_fundoDAL.MovePatrimony(id.ToString(), value))
                    return RedirectToAction("Index");
                else
                    throw new ArgumentException(Constants.ValueNotUpdate());

            }
            catch (ArgumentException ex)
            {
                ViewBag.Alert = ex.Message;
                return View("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Alert = Constants.Error();
                return View("Index");
            }
        }
        public ActionResult Delete(int id)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();
                if (_fundoDAL.RemoveFundo(id.ToString()))
                    return RedirectToAction("Index");
                else
                    throw new ArgumentException(Constants.FundNotRemove());
            }
            catch (ArgumentException ex)
            {
                ViewBag.Alert = ex.Message;
                return View("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Alert = Constants.Error();
                return View("Index");
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }
    }
}

CaseItauWeb/Views/Fundo/Create.cshtml
@model CaseItauWeb.Models.FundoModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "_Layout";
}
@{
    ViewData["Title"] = "Create";
}

    <h2>Cadastro de novos fundos</h2>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Register" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Nome" class="control-label">Nome</label>
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Cnpj" class="control-label">Cnpj</label>
                    <input asp-for="Cnpj" class="form-control" />
                    <span asp-validation-for="Cnpj" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CodigoTipo.NomeTipo" class="control-label">Tipo</label>
                    <input asp-for="CodigoTipo.NomeTipo" class="form-control" />
                    <span asp-validation-for="CodigoTipo.NomeTipo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Patrimonio" class="control-label">Patrimonio</label>
                    <input asp-for="Patrimonio" class="form-control" />
                    <span asp-validation-for="Patrimonio" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Registrar" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-controle="Register" asp-action="Index">@Html.ActionLink("Retornar", "Index", new { /* id=item.PrimaryKey */ })</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

CaseItauWeb/Views/Fundo/Edit.cshtml
@model CaseItauWeb.Models.FundoModel
@{
    Layout = "_Layout";
}
@{
    ViewData["Title"] = "Edit";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h1>Editar dados do fundo</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" value="@Model.Nome"/>
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cnpj" class="control-label"></label>
                <input asp-for="Cnpj" class="form-control" value="@Model.Cnpj"/>
                <span asp-validation-for="Cnpj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodigoTipo.NomeTipo" class="control-label"></label>
                <input asp-for="CodigoTipo.NomeTipo" class="form-control"  value="@Model.CodigoTipo.NomeTipo"/>
                <span asp-validation-for="CodigoTipo.NomeTipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retornar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CaseItauWeb/Views/Fundo/EditPatrimony.cshtml
@model CaseItauWeb.Models.FundoModel
@{
    Layout = "_Layout";
}
@{
    ViewData["Title"] = "Editar Patrimonio";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers


<h1>Editar Patrimonio</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditPatrimony" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" value="@Model.Nome" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cnpj" class="control-label"></label>
                <input asp-for="Cnpj" class="form-control" value="@Model.Cnpj"/>
                <span asp-validation-for="Cnpj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patrimonio" class="control-label"></label>
                <input asp-for="Patrimonio" class="form-control" value="@Model.Patrimonio"/>
                <span asp-validation-for="Patrimonio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retornar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CaseItauWeb/Views/Fundo/Index.cshtml
@model IEnumerable<CaseItauWeb.Models.FundoModel>
@{
    Layout = "_Layout";
}
@{
    ViewData["Title"] = "Index";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<h1>Fundos Cadastrados</h1>
@if (ViewBag.Alert != null)
{
    <div class="alert alert-dismissible alert-primary">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <a href="#" class="alert-link"></a> @ViewBag.Alert.
    </div>
    <div>
        <a asp-action="Index">Retornar</a>
    </div>
}
else
{
    <p>
        @*<a href="" asp-controle="Register" asp-action="Create">Cadastrar Novo Fundo</a>*@
        <a asp-controller="Fundo" asp-action="Create" class="btn btn-light">Cadastrar Novo Fundo</a>

    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cnpj)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Patrimonio)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CodigoTipo.NomeTipo)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cnpj)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Patrimonio)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CodigoTipo.NomeTipo)
                    </td>
                    <td>
                        @Html.ActionLink("Editar", "Edit", new { id = item.Codigo }) |
                        @Html.ActionLink("Alterar Patrimonio", "EditPatrimony", new { id = item.Codigo }) |
                        @Html.ActionLink("Excluir", "Delete", new { id = item.Codigo })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}